[build]
  base = "/"
  publish = "dist/"
  command = "yarn build"
  functions = "functions"

[template.environment]
  REACT_APP_BACKEND_URL = ".netlify/functions/server"
  PORT = 3002
  MONGODB = "mongodb+srv://monstertrain:R99vkfAyh8oElFbj@mtmdb-axxqj.mongodb.net/monstertrain?retryWrites=true&w=majority"
